# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e977402b0517e07b340c8c5d3b9603e5c01dbe54089eb3ee7669cb8ff9da1c7f08be1e190ee7e0518d7d879ee56ca954f60e2e14ce202e57554dbb7d7d4eab3

test:
  secret_key_base: a4f99cc036fbecdc1c32c0f0cc78e6deb423148c8970197f5da818a7adc270eb31d6c633b713c5e0df146a39846f54ee9adaa4ace7b5cb05610fee7299e58db6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
